Add /quest tolocation command
Atherys-Horizons/AtherysQuests pull request #9
Opened 2018-05-09 14:53 UTC by LJNIC

2018-05-09 18:11 UTC, HaedHutner requested changes

2018-05-09 18:11 UTC, HaedHutner commented on src/main/java/com/atherys/quests/commands/quest/AttachQuestToLocationCommand.java
> +public class AttachQuestToLocationCommand implements CommandExecutor, ParameterizedCommand {
There's no need to implement both CommandExecutor and ParameterizedCommand, as ParameterizedCommand already extends CommandExecutor

2018-05-09 18:11 UTC, HaedHutner commented on src/main/java/com/atherys/quests/listeners/EntityListener.java
> +        if(LocationManager.getInstance().getByLocation(e.getFromTransform().getLocation()).isPresent()) return;
Check whether or not the position of the player is the same between transforms to avoid unnecessary work being done by the plugin

2018-05-09 18:11 UTC, HaedHutner commented on src/main/java/com/atherys/quests/managers/LocationManager.java
> +    private static Gson gson = GsonUtils.getGson();
Ideally, getGson would be called during initialization of the LocationManager. Having it as a static field introduces possible ndefined behaviors.

2018-05-09 18:11 UTC, HaedHutner commented on src/main/java/com/atherys/quests/managers/LocationManager.java
> +    public boolean addLocationQuest(Location<World> location, String questId, double radius){
addQuestLocation may be a better name here?

2018-05-09 18:11 UTC, HaedHutner commented on src/main/java/com/atherys/quests/managers/LocationManager.java
> +        private boolean overlaps(QuestLocation questLocation){
use Vector3d#distanceSquared() for better performance, sqrt is a heavier operation than squaring the radius you wish to compare against

2018-05-12 12:26 UTC, LJNIC commented
This PR fixed #1 and added QuestLocation's. But my mongo database is doubling the amount of QuestLocation's every shutdown, and I don't know why.

2018-05-19 20:40 UTC, HaedHutner requested changes

2018-05-19 20:40 UTC, HaedHutner commented on src/main/java/com/atherys/quests/managers/LocationManager.java
> +        Document location = DbUtils.Serialize.location(questLocation.location);
If you have registered a ConfigurateAdapter<Location> within the Gson instance, there is no need for DbUtils.

2018-05-19 20:40 UTC, HaedHutner commented on src/main/java/com/atherys/quests/managers/LocationManager.java
> +        document.append("radius", questLocation.radius);
Please access these fields using getters. Also, create getters for them. Don't need to make setters, a QuestLocation can be Immutable, that would be just fine, but accessing them directly like this is quite ugly and not very safe.

2018-05-22 16:17 UTC, HaedHutner approved these changes

2018-05-22 16:18 UTC, merged